name: "Build cdrdao2wav"

on:
  push:
  pull_request:

jobs:
  build:
    name: "Build ${{ matrix.goos }}/${{ matrix.goarch }}"
    runs-on: "${{ matrix.runs-on }}"

    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: "linux"
            goarch: "amd64"
            artifact: "cdrdao2wav-linux-amd64"
            runs-on: "ubuntu-latest"

          - goos: "linux"
            goarch: "arm64"
            artifact: "cdrdao2wav-linux-arm64"
            runs-on: "ubuntu-latest"

          - goos: "windows"
            goarch: "amd64"
            artifact: "cdrdao2wav-windows-amd64.exe"
            runs-on: "windows-latest"

          - goos: "windows"
            goarch: "arm64"
            artifact: "cdrdao2wav-windows-arm64.exe"
            runs-on: "windows-latest"

          - goos: "darwin"
            goarch: "arm64"
            artifact: "cdrdao2wav-macos-arm64"
            runs-on: "macos-latest"

          - goos: "darwin"
            goarch: "amd64"
            artifact: "cdrdao2wav-macos-amd64"
            runs-on: "macos-latest"

    steps:
      - name: "Check out source code"
        uses: "actions/checkout@v7.0.0"

      - name: "Set up Go"
        uses: "actions/setup-go@v6.4.0"
        with:
          go-version: "1.26.4"
          cache: false

      - name: "Download dependencies"
        run: "go mod download"

      - name: "Test and build cdrdao2wav for ${{ matrix.goos }}/${{ matrix.goarch }}"
        shell: "bash"
        env:
          GOOS: "${{ matrix.goos }}"
          GOARCH: "${{ matrix.goarch }}"
        run: |
          make release

      - name: "Upload build artifact"
        uses: "actions/upload-artifact@v7.0.1"
        with:
          name: "${{ matrix.artifact }}"
          path: "build/bin/cdrdao2wav${{ matrix.goos == 'windows' && '.exe' || '' }}"
